variable "aws_ebs_size" {}
variable "aws_instance_type" {}
variable "aws_key" {}
variable "aws_key_name" {}
variable "aws_region" {}
variable "aws_region" {}
variable "aws_secgroup_name" {}
variable "aws_secret" {}
variable "kraken_ci_hostname" {}
variable "clusters_bucket" {}
variable "coreos_channel" {}
variable "coreos_reboot_strategy" {}
variable "coreos_version" {}
variable "docker_api_version" {}
variable "github_client_id" {}
variable "github_client_key" {}
variable "jenkins_ssh_key" {}
variable "private_jenkins_ssh_key" {}
variable "route53_zone_id" {}
